spring:
  datasource:
  
# project
    url: jdbc:mysql://14.63.166.136/test6?useUnicode=true&characterEncoding=utf-8
    username: pandora_ojt
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

# prac
#    url: jdbc:mysql://localhost:3306/prac?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/prac?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: system
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
    
server:
  port: 8085
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# mybatis 매핑
mybatis:
  type-aliases-package: com.example.demo.model
  mapper-locations: mybatis/mapper/**/*.xml 
  
  
  
  
  
    
  